
franciscosuca/countdown:
  - source: templates/js/.releaserc.json
    dest: .releaserc.json
  - source: templates/js/cloudbuild.yaml
    dest: cloudbuild.yaml
  - source: templates/js/.github/workflows/build-and-release.yml
    dest: .github/workflows/build-and-release.yml

franciscosuca/martech:
  - source: templates/js/.releaserc.json
    dest: .releaserc.json
  - source: templates/js/cloudbuild.yaml
    dest: cloudbuild.yaml
  - source: templates/js/.github/workflows/build-and-release.yml
    dest: .github/workflows/build-and-release.yml