name: Sync files to consumer repos

on:
  push:
    branches:
      - main
    paths:
      - '.templates/.net/**'
      - '.templates/js/**'
      - '.templates/py/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}